version: '3'

services:

  laravel:
    build:
      context: ./php
      dockerfile: Dockerfile.prod
    image: thiagoalvesfoz/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: thiagoalvesfoz/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge